#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname "$0")" && pwd)
PROJECT_ROOT=${PROJECT_ROOT:-$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)}
. "$SCRIPT_DIR/common.sh"

output=${1:-}
[ -n "$output" ] || die 'Usage: render-config.sh OUTPUT_DIRECTORY'
[ ! -e "$output" ] || die "Render destination already exists: $output"
mkdir -p "$output"
parsed=$output/.global.parsed
config_parse "$PROJECT_ROOT/.env" "$GLOBAL_KEYS" "$parsed"
validate_global_config "$parsed"

host_id=$(config_get "$parsed" HOST_ID)
environment=$(config_get "$parsed" ENVIRONMENT)
auth_enabled=$(config_get "$parsed" OBSERVABILITY_AUTH_ENABLED)
access_log=$(config_get "$parsed" NGINX_ACCESS_LOG)
error_log=$(config_get "$parsed" NGINX_ERROR_LOG)
open_ports=$(config_get "$parsed" BEYLA_OPEN_PORTS)
containers_only=$(config_get "$parsed" BEYLA_CONTAINERS_ONLY)

copy_template() { cp "$PROJECT_ROOT/alloy/templates/$1" "$output/$1"; }
replace_token() {
    file=$1 token=$2 value=$3
    escaped=$(printf '%s' "$value" | sed 's/[\/&]/\\&/g')
    sed "s/@$token@/$escaped/g" "$file" >"$file.tmp"
    mv "$file.tmp" "$file"
}

copy_template 00-base.alloy
copy_template 10-outputs.alloy
replace_token "$output/10-outputs.alloy" HOST_ID "$(alloy_escape "$host_id")"
replace_token "$output/10-outputs.alloy" ENVIRONMENT "$(alloy_escape "$environment")"
if is_true "$auth_enabled"; then
    sed '/\/\/ AUTH_BEGIN/d; /\/\/ AUTH_END/d' "$output/10-outputs.alloy" >"$output/10-outputs.alloy.tmp"
else
    sed '/\/\/ AUTH_BEGIN/,/\/\/ AUTH_END/d' "$output/10-outputs.alloy" >"$output/10-outputs.alloy.tmp"
fi
mv "$output/10-outputs.alloy.tmp" "$output/10-outputs.alloy"

is_true "$(config_get "$parsed" ENABLE_HOST_METRICS)" && copy_template 20-host.alloy
is_true "$(config_get "$parsed" ENABLE_DOCKER_METRICS)" && copy_template 30-docker-metrics.alloy
is_true "$(config_get "$parsed" ENABLE_DOCKER_LOGS)" && copy_template 40-docker-logs.alloy
if is_true "$(config_get "$parsed" ENABLE_NGINX_LOGS)"; then
    copy_template 50-nginx-logs.alloy
    replace_token "$output/50-nginx-logs.alloy" ACCESS_LOG "$(alloy_escape "$access_log")"
    replace_token "$output/50-nginx-logs.alloy" ERROR_LOG "$(alloy_escape "$error_log")"
fi
if is_true "$(config_get "$parsed" ENABLE_BEYLA)"; then
    copy_template 60-beyla.alloy
    replace_token "$output/60-beyla.alloy" OPEN_PORTS "$open_ports"
    replace_token "$output/60-beyla.alloy" CONTAINERS_ONLY "$containers_only"
fi

: >"$output/agent.env"
for key in PROMETHEUS_WRITE_URL LOKI_WRITE_URL OBSERVABILITY_USERNAME OBSERVABILITY_PASSWORD DOCKER_HOST; do
    env_write "$key" "$(config_get "$parsed" "$key")" "$output/agent.env"
done

seen_postgres=' '; seen_mysql=' '; seen_redis=' '
for file in "$PROJECT_ROOT/instances/postgres/"*.env; do
    [ -f "$file" ] || continue
    values=$output/.instance.parsed
    config_parse "$file" "$POSTGRES_KEYS" "$values"
    for key in NAME DSN AUTODISCOVERY APP SERVICE; do require_config "$values" "$key"; done
    name=$(config_get "$values" NAME); id=$(alloy_identifier "$name"); env_id=$(env_identifier "$id")
    [ -n "$id" ] || die "Invalid PostgreSQL NAME in $file"
    case "$seen_postgres" in *" $id "*) die "Duplicate PostgreSQL component identifier: $id" ;; esac
    seen_postgres="$seen_postgres$id "
    validate_bool AUTODISCOVERY "$(config_get "$values" AUTODISCOVERY)"
    env_write "POSTGRES_${env_id}_DSN" "$(config_get "$values" DSN)" "$output/agent.env"
    src=$(basename "$file")
    cat >"$output/70-postgres-$id.alloy" <<EOF
// Generated by per-host-observe. Source: instances/postgres/$src. Do not edit.
prometheus.exporter.postgres "$id" {
  data_source_names = [sys.env("POSTGRES_${env_id}_DSN")]
  autodiscovery { enabled = $(config_get "$values" AUTODISCOVERY) }
}
discovery.relabel "postgres_$id" {
  targets = prometheus.exporter.postgres.$id.targets
  rule {
    target_label = "db_instance"
    replacement = "$(alloy_escape "$name")"
  }
  rule {
    target_label = "app"
    replacement = "$(alloy_escape "$(config_get "$values" APP)")"
  }
  rule {
    target_label = "service"
    replacement = "$(alloy_escape "$(config_get "$values" SERVICE)")"
  }
}
prometheus.scrape "postgres_$id" {
  targets = discovery.relabel.postgres_$id.output
  forward_to = [prometheus.relabel.identity.receiver]
}
EOF
done

for file in "$PROJECT_ROOT/instances/mysql/"*.env; do
    [ -f "$file" ] || continue
    values=$output/.instance.parsed
    config_parse "$file" "$MYSQL_KEYS" "$values"
    for key in NAME DSN APP SERVICE; do require_config "$values" "$key"; done
    name=$(config_get "$values" NAME); id=$(alloy_identifier "$name"); env_id=$(env_identifier "$id")
    [ -n "$id" ] || die "Invalid MySQL NAME in $file"
    case "$seen_mysql" in *" $id "*) die "Duplicate MySQL component identifier: $id" ;; esac
    seen_mysql="$seen_mysql$id "
    env_write "MYSQL_${env_id}_DSN" "$(config_get "$values" DSN)" "$output/agent.env"
    src=$(basename "$file")
    cat >"$output/80-mysql-$id.alloy" <<EOF
// Generated by per-host-observe. Source: instances/mysql/$src. Do not edit.
prometheus.exporter.mysql "$id" { data_source_name = sys.env("MYSQL_${env_id}_DSN") }
discovery.relabel "mysql_$id" {
  targets = prometheus.exporter.mysql.$id.targets
  rule {
    target_label = "db_instance"
    replacement = "$(alloy_escape "$name")"
  }
  rule {
    target_label = "app"
    replacement = "$(alloy_escape "$(config_get "$values" APP)")"
  }
  rule {
    target_label = "service"
    replacement = "$(alloy_escape "$(config_get "$values" SERVICE)")"
  }
}
prometheus.scrape "mysql_$id" {
  targets = discovery.relabel.mysql_$id.output
  forward_to = [prometheus.relabel.identity.receiver]
}
EOF
done

for file in "$PROJECT_ROOT/instances/redis/"*.env; do
    [ -f "$file" ] || continue
    values=$output/.instance.parsed
    config_parse "$file" "$REDIS_KEYS" "$values"
    for key in NAME ADDRESS APP SERVICE; do require_config "$values" "$key"; done
    name=$(config_get "$values" NAME); id=$(alloy_identifier "$name"); env_id=$(env_identifier "$id")
    [ -n "$id" ] || die "Invalid Redis NAME in $file"
    case "$seen_redis" in *" $id "*) die "Duplicate Redis component identifier: $id" ;; esac
    seen_redis="$seen_redis$id "
    env_write "REDIS_${env_id}_ADDRESS" "$(config_get "$values" ADDRESS)" "$output/agent.env"
    env_write "REDIS_${env_id}_USERNAME" "$(config_get "$values" USERNAME)" "$output/agent.env"
    env_write "REDIS_${env_id}_PASSWORD" "$(config_get "$values" PASSWORD)" "$output/agent.env"
    src=$(basename "$file")
    cat >"$output/90-redis-$id.alloy" <<EOF
// Generated by per-host-observe. Source: instances/redis/$src. Do not edit.
prometheus.exporter.redis "$id" {
  redis_addr = sys.env("REDIS_${env_id}_ADDRESS")
  redis_user = sys.env("REDIS_${env_id}_USERNAME")
  redis_password = sys.env("REDIS_${env_id}_PASSWORD")
}
discovery.relabel "redis_$id" {
  targets = prometheus.exporter.redis.$id.targets
  rule {
    target_label = "db_instance"
    replacement = "$(alloy_escape "$name")"
  }
  rule {
    target_label = "app"
    replacement = "$(alloy_escape "$(config_get "$values" APP)")"
  }
  rule {
    target_label = "service"
    replacement = "$(alloy_escape "$(config_get "$values" SERVICE)")"
  }
}
prometheus.scrape "redis_$id" {
  targets = discovery.relabel.redis_$id.output
  forward_to = [prometheus.relabel.identity.receiver]
}
EOF
done

http_address=$(config_get "$parsed" ALLOY_HTTP_ADDRESS)
rm -f "$output/.global.parsed" "$output/.instance.parsed"
cat >"$output/alloy.defaults" <<EOF
CONFIG_FILE="/etc/alloy/per-host-observe"
CUSTOM_ARGS="--server.http.listen-addr=$http_address"
RESTART_ON_UPGRADE=true
EOF
chmod 600 "$output/agent.env"
info "Rendered configuration to $output"
